version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.15.6
    working_directory: /go/src/github.com/influxdata/influxdata-docker
    steps:
      - checkout
      - setup_remote_docker
      - run: bash circle-test.sh

  test-influxdb:
    docker:
      - image: cimg/go:1.15.6
    working_directory: /go/src/github.com/influxdata/influxdata-docker
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: bash influxdb/circle-test.sh
